In [17]:
import pandas as pd
import numpy as np

In [90]:
df=pd.read_csv("creditcard.csv")

In [91]:
df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [92]:
df.shape

(284807, 31)

In [93]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [94]:
df.Class.value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [95]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [96]:
from sklearn.model_selection import train_test_split,GridSearchCV,KFold
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [32]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
grid={'C':10.0**(np.arange(-2,3)),'penalty':["l1","l2"]}
cv=KFold()
clf=GridSearchCV(lr,grid,cv=cv,n_jobs=-1,scoring='f1_macro')
clf.fit(x_train,y_train)

c:\users\pradn\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [33]:
y_pred=clf.predict(x_test)

In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
confusion_matrix(y_test,y_pred)

array([[85264,    32],
       [   47,   100]], dtype=int64)

In [35]:
accuracy_score(y_test,y_pred)

0.9990754069964772

In [37]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85296
           1       0.76      0.68      0.72       147

    accuracy                           1.00     85443
   macro avg       0.88      0.84      0.86     85443
weighted avg       1.00      1.00      1.00     85443



In [41]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(n_estimators=500,criterion="entropy")
cls.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=500)

In [65]:
y_pred=cls.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[66341 18956]
 [    3   143]]
0.7781093828634295
              precision    recall  f1-score   support

           0       1.00      0.78      0.87     85297
           1       0.01      0.98      0.01       146

    accuracy                           0.78     85443
   macro avg       0.50      0.88      0.44     85443
weighted avg       1.00      0.78      0.87     85443



# undersampling

In [55]:

from collections import Counter 
from imblearn.under_sampling import NearMiss

In [56]:
ns=NearMiss(0.8)
x_tr,y_tr=ns.fit_sample(x_train,y_train)

c:\users\pradn\appdata\local\programs\python\python38\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [62]:
print(f" {Counter(y_train)}")

 Counter({0: 199018, 1: 346})


In [63]:
print(f"{Counter(y_tr)}")

Counter({0: 437, 1: 350})


In [76]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(n_estimators=500,criterion="entropy")
cls.fit(x_tra,y_tra)

KeyboardInterrupt: 

In [66]:
y_pred=cls.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[66341 18956]
 [    3   143]]
0.7781093828634295
              precision    recall  f1-score   support

           0       1.00      0.78      0.87     85297
           1       0.01      0.98      0.01       146

    accuracy                           0.78     85443
   macro avg       0.50      0.88      0.44     85443
weighted avg       1.00      0.78      0.87     85443



# over sampling


In [67]:
from imblearn.over_sampling import RandomOverSampler

In [77]:
over=RandomOverSampler(0.75)

c:\users\pradn\appdata\local\programs\python\python38\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [78]:
x_tra,y_tra=over.fit_sample(x_train,y_train)

In [79]:
print(f"{Counter(y_train)}")
print(f"{Counter(y_tra)}")

Counter({0: 199018, 1: 346})
Counter({0: 199018, 1: 149263})


In [80]:
199018/2

99509.0

In [81]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(n_estimators=100,criterion="entropy")
cls.fit(x_tra,y_tra)

RandomForestClassifier(criterion='entropy')

In [83]:
y_pred=cls.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85289     8]
 [   34   112]]
0.9995084442259752
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85297
           1       0.93      0.77      0.84       146

    accuracy                           1.00     85443
   macro avg       0.97      0.88      0.92     85443
weighted avg       1.00      1.00      1.00     85443



# SMOTomek

In [99]:
from imblearn.combine import SMOTETomek
s=SMOTETomek(0.75)

c:\users\pradn\appdata\local\programs\python\python38\lib\site-packages\imblearn\utils\_validation.py:635: FutureWarning: Pass sampling_strategy=0.75 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.9 "


In [100]:
xt,yt=s.fit_sample(x_train,y_train)

In [101]:
print(f"{Counter(y_train)}")
print(f"{Counter(yt)}")

Counter({0: 199018, 1: 346})
Counter({0: 198323, 1: 148568})


In [103]:
from sklearn.ensemble import RandomForestClassifier
cls=RandomForestClassifier(n_estimators=100,criterion="entropy")
cls.fit(xt,yt)

RandomForestClassifier(criterion='entropy')

In [105]:
y_pred=cls.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[85278    19]
 [   25   121]]
0.9994850368081645
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85297
           1       0.86      0.83      0.85       146

    accuracy                           1.00     85443
   macro avg       0.93      0.91      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [1]:
from imblearn.ensemble import EasyEnsembleClassifier

In [2]:
easy=EasyEnsembleClassifier()
easy.fit(x_train,y_train)

NameError: name 'x_train' is not defined